### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by zengwenfu** [zengwenfu/muti-html-webpack-plugin#1]
欢迎反馈问题

**Comment by 8427003** [comment]
buffer.js:257
  throw new TypeError(kFromErrorMsg);
  ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:257:9)
    at Function.Buffer.from (buffer.js:97:10)
    at new Buffer (buffer.js:76:17)
    at Compiler.writeOut (/Users/lijun/git/webpacktest/node_modules/webpack/lib/Compiler.js:258:16)
    at Compiler.<anonymous> (/Users/lijun/git/webpacktest/node_modules/webpack/lib/Compiler.js:246:20)
    at /Users/lijun/git/webpacktest/node_modules/webpack/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/Users/lijun/git/webpacktest/node_modules/webpack/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/Users/lijun/git/webpacktest/node_modules/webpack/node_modules/async/lib/async.js:209:22)
    at Compiler.emitFiles (/Users/lijun/git/webpacktest/node_modules/webpack/lib/Compiler.js:235:20)
    at /Users/lijun/git/webpacktest/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by 8427003** [comment]
var MutiHtmlWebpackPlugin = require('muti-html-webpack-plugin');
 12 const paths = [
 13      './xxx/news.html'
 14 ];
 15
 16 var config = {
 17     entry: {main: './index.js'},
 18     output: {
 19        filename: 'bundle.js',
 20        path: 'dist'
 21     },
 22     plugins: [
 23        new ExtractTextPlugin('styles/[name].css'),
 24        new MutiHtmlWebpackPlugin({
 25           templatePath: './views',
 26           templateSuffix: '.html',
 27           path: '/dist'
 28        })
 29     ],
 30     module: {

**Comment by twoer** [comment]
哥，你的 path 是啥意思，写个说明啊！
